[package]
name = "catr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
pretty_assertions = "1.4.1"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "2"
rand = "0.8.5"
